package com.revature.beans;

import java.io.Serializable;
import java.util.List;

public class User implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 9006770911805384520L;
	
	private Integer uid;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String email;
	private Integer uroleid;
	private List<Reimbs> reimbs;
	
	//no args constructor
	public User() {
		
	}
	//all args constructor (without autogenerated uid)
	public User(String username, String password, String firstName, String lastName, String email, Integer uroleid,
			List<Reimbs> reimbs) {
		super();
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.uroleid = uroleid;
		this.reimbs = reimbs;
	}
	//all args constructor
	public User(Integer uid, String username, String password, String firstName, String lastName, String email,
			Integer uroleid, List<Reimbs> reimbs) {
		super();
		this.uid = uid;
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.uroleid = uroleid;
		this.reimbs = reimbs;
	}
	public Integer getUid() {
		return uid;
	}
	public void setUid(Integer uid) {
		this.uid = uid;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public Integer getUroleid() {
		return uroleid;
	}
	public void setUroleid(Integer uroleid) {
		this.uroleid = uroleid;
	}
	public List<Reimbs> getReimbs() {
		return reimbs;
	}
	public void setReimbs(List<Reimbs> reimbs) {
		this.reimbs = reimbs;
	}
	@Override
	public String toString() {
		return "User [uid=" + uid + ", username=" + username + ", password=" + password + ", firstName=" + firstName
				+ ", lastName=" + lastName + ", email=" + email + ", uroleid=" + uroleid + ", reimbs=" + reimbs + "]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((firstName == null) ? 0 : firstName.hashCode());
		result = prime * result + ((lastName == null) ? 0 : lastName.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((reimbs == null) ? 0 : reimbs.hashCode());
		result = prime * result + ((uid == null) ? 0 : uid.hashCode());
		result = prime * result + ((uroleid == null) ? 0 : uroleid.hashCode());
		result = prime * result + ((username == null) ? 0 : username.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (firstName == null) {
			if (other.firstName != null)
				return false;
		} else if (!firstName.equals(other.firstName))
			return false;
		if (lastName == null) {
			if (other.lastName != null)
				return false;
		} else if (!lastName.equals(other.lastName))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (reimbs == null) {
			if (other.reimbs != null)
				return false;
		} else if (!reimbs.equals(other.reimbs))
			return false;
		if (uid == null) {
			if (other.uid != null)
				return false;
		} else if (!uid.equals(other.uid))
			return false;
		if (uroleid == null) {
			if (other.uroleid != null)
				return false;
		} else if (!uroleid.equals(other.uroleid))
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		return true;
	}
	
}
	
	